steps:
- name: 'postgres'
  env: ['POSTGRES_PASSWORD=test1234']
  entrypoint: 'bash'
  #args: ['bash', 'workspace/postgres.sh']
  args: ['-c', '/docker-entrypoint.sh; chmod 755 ./postgres.sh; ./postgres.sh; ps -aef']
