steps:
- name: 'postgres'
  #env: ['POSTGRES_PASSWORD=postgres']
  entrypoint: 'bash'
  #args: ['bash', 'workspace/postgres.sh']
  #args: ['-c', '/docker-entrypoint.sh; chmod 755 ./postgres.sh; ./postgres.sh' ]
  args: ['-x', '/docker-entrypoint.sh', 'postgres']
  id: A
  waitFor: ['-']
  
- name: 'postgres'
  entrypoint: 'bash'
  args: ['chmod 755 ./client.sh ; ./client.sh']
  id: B
  waitFor: ['-']
